"""
scripts/seed_usecases.py — Populate database with initial usecase catalog.
Run with: python -c "from scripts.seed_usecases import seed_usecases; seed_usecases()"
Or in Flask shell: from scripts.seed_usecases import seed_usecases; seed_usecases()
"""
from app import db
from app.models.usecase import UsecaseCategory, Usecase


# Category definitions (from usecases.js)
CATEGORIES_DATA = [
    {
        "key": "tabular",
        "label": "Tabular & Structured Data",
        "blurb": "Classify rows, predict numbers, score risk, recommend items — anything where each example is a feature vector.",
        "icon": "table",
        "color": "var(--cat-tabular)",
        "order": 0,
    },
    {
        "key": "vision",
        "label": "Computer Vision",
        "blurb": "Deep learning models for image-only data — classification, detection, segmentation, generation.",
        "icon": "image",
        "color": "var(--cat-vision)",
        "order": 1,
    },
    {
        "key": "nlp",
        "label": "Natural Language Processing",
        "blurb": "Text models — classification, similarity, question answering, NER, summarization.",
        "icon": "text",
        "color": "var(--cat-nlp)",
        "order": 2,
    },
    {
        "key": "audio",
        "label": "Audio & Speech",
        "blurb": "Speech recognition, audio classification, keyword spotting, voice cloning.",
        "icon": "music",
        "color": "var(--cat-audio)",
        "order": 3,
    },
    {
        "key": "timeseries",
        "label": "Time Series & Forecasting",
        "blurb": "Predict the future — sales, sensors, prices, demand, anomalies.",
        "icon": "activity",
        "color": "var(--cat-timeseries)",
        "order": 4,
    },
    {
        "key": "generative",
        "label": "Generative & Diffusion",
        "blurb": "Generate new images, text, audio — VAEs, GANs, diffusion, autoregressive.",
        "icon": "spark",
        "color": "var(--cat-generative)",
        "order": 5,
    },
    {
        "key": "rl",
        "label": "Reinforcement Learning",
        "blurb": "Train agents that learn by doing — games, control, recommendations.",
        "icon": "target",
        "color": "var(--cat-rl)",
        "order": 6,
    },
    {
        "key": "graph",
        "label": "Graph & Network",
        "blurb": "Models over graphs — molecules, social networks, fraud, knowledge graphs.",
        "icon": "network",
        "color": "var(--cat-graph)",
        "order": 7,
    },
    {
        "key": "multimodal",
        "label": "Multimodal",
        "blurb": "Combine modalities — vision+language, audio+text, sensor fusion.",
        "icon": "layers",
        "color": "var(--cat-multimodal)",
        "order": 8,
    },
    {
        "key": "tools",
        "label": "Foundations & Experiments",
        "blurb": "Toy problems, classic benchmarks, and from-scratch experiments to build intuition.",
        "icon": "flask",
        "color": "var(--cat-tools)",
        "order": 9,
    },
]

# Usecase definitions (from usecases.js)
USECASES_DATA = [
    # Tabular
    {
        "cat": "tabular",
        "key": "tab_classify",
        "icon": "table",
        "title": "Tabular Classification",
        "desc": "Classify rows into 2+ categories — e.g. categorize flowers by petal size, churn vs retain, fraud vs legit.",
        "tags": "Local",
        "starter": {"arch": "mlp", "loss": "ce", "layers": ["Dense(64)", "ReLU", "Dropout(0.2)", "Dense(num_classes)"]},
    },
    {
        "cat": "tabular",
        "key": "tab_regression",
        "icon": "chart",
        "title": "Value Prediction (Regression)",
        "desc": "Predict a numeric value from features — house price from size & location, demand from price & season.",
        "tags": "Local",
        "starter": {"arch": "mlp", "loss": "mse", "layers": ["Dense(64)", "ReLU", "Dense(32)", "ReLU", "Dense(1)"]},
    },
    {
        "cat": "tabular",
        "key": "tab_recommend",
        "icon": "star",
        "title": "Recommendation",
        "desc": "Suggest items for a user — products, movies, content. Two-tower or matrix-factorization starters.",
        "tags": "Local,Preview",
        "starter": {"arch": "mlp", "loss": "bce"},
    },
    {
        "cat": "tabular",
        "key": "tab_anomaly",
        "icon": "target",
        "title": "Anomaly Detection",
        "desc": "Find unusual rows in tabular data — fraud, sensor faults, billing anomalies. Autoencoder or isolation forest.",
        "tags": "Local",
        "starter": {"arch": "autoencoder", "loss": "mse"},
    },
    {
        "cat": "tabular",
        "key": "tab_credit",
        "icon": "binary",
        "title": "Credit Risk Scoring",
        "desc": "Predict default probability from credit-line features. Calibrated probabilities + per-segment metrics.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "tabular",
        "key": "tab_survival",
        "icon": "activity",
        "title": "Survival Analysis",
        "desc": "Time-to-event modeling — churn timing, equipment failure. Cox PH neural-net starter.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "tabular",
        "key": "tab_imputation",
        "icon": "eraser",
        "title": "Missing-Value Imputation",
        "desc": "Fill in NaNs across a dataset using a denoising autoencoder.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "tabular",
        "key": "tab_clustering",
        "icon": "grid",
        "title": "Unsupervised Clustering",
        "desc": "Group similar rows without labels — customer segments, behavior cohorts. Deep embedding + k-means.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # Vision (10 total)
    {
        "cat": "vision",
        "key": "img_classify",
        "icon": "image",
        "title": "Image Classification",
        "desc": "Classify images into 2+ categories — dog vs cat, defect vs ok, leaf disease.",
        "tags": "Local,Cloud",
        "starter": {"arch": "cnn"},
    },
    {
        "cat": "vision",
        "key": "img_detect",
        "icon": "target",
        "title": "Object Detection",
        "desc": "Detect & locate objects — cars, faces, defects. Returns bounding boxes per class.",
        "tags": "Local,Cloud,Preview",
        "starter": {"arch": "cnn"},
    },
    {
        "cat": "vision",
        "key": "img_segment",
        "icon": "layers",
        "title": "Semantic Segmentation",
        "desc": "Label every pixel — medical imaging, satellite, scene parsing. UNet starter.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "vision",
        "key": "img_pose",
        "icon": "user",
        "title": "Pose Estimation",
        "desc": "Detect keypoints on bodies, hands, faces — fitness apps, sign language, motion capture.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "vision",
        "key": "img_ocr",
        "icon": "text",
        "title": "OCR / Text Detection",
        "desc": "Read text from images — receipts, documents, license plates.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "vision",
        "key": "img_super",
        "icon": "spark",
        "title": "Super-Resolution",
        "desc": "Upscale low-res images to high-res. ESRGAN-style starter.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "vision",
        "key": "img_depth",
        "icon": "cube",
        "title": "Monocular Depth Estimation",
        "desc": "Predict depth from a single image. AR, robotics, scene understanding.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "vision",
        "key": "img_style",
        "icon": "spark",
        "title": "Style Transfer",
        "desc": "Apply the style of one image to the content of another.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "vision",
        "key": "img_face",
        "icon": "user",
        "title": "Face Recognition / Verification",
        "desc": "Identity verification with embedding networks (siamese / triplet loss).",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "vision",
        "key": "img_anomaly",
        "icon": "target",
        "title": "Visual Anomaly Detection",
        "desc": "Find defects in manufacturing imagery without labeled defect examples.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # NLP (10 total)
    {
        "cat": "nlp",
        "key": "nlp_classify",
        "icon": "text",
        "title": "Text Classification",
        "desc": "Assign a label to text — sentiment of reviews, topic of articles, intent of queries.",
        "tags": "Local,Cloud",
        "starter": {"arch": "transformer"},
    },
    {
        "cat": "nlp",
        "key": "nlp_similarity",
        "icon": "fork",
        "title": "Sentence Similarity",
        "desc": "Score how similar two sentences are. Search ranking, deduplication, semantic FAQ.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_qa",
        "icon": "chat",
        "title": "Question Answering",
        "desc": "Answer questions over a passage of text. Extractive QA starter.",
        "tags": "Local,Cloud",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_ner",
        "icon": "tree",
        "title": "Named Entity Recognition",
        "desc": "Tag tokens as people, places, organizations, custom entities.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_summarize",
        "icon": "book",
        "title": "Summarization",
        "desc": "Compress documents into short summaries — abstractive or extractive.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_translate",
        "icon": "fork",
        "title": "Translation",
        "desc": "Translate text between languages. Encoder-decoder starter.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_lm",
        "icon": "chat",
        "title": "Language Modeling (next-token)",
        "desc": "Train a small autoregressive LM on your own corpus. GPT-style starter.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_topic",
        "icon": "grid",
        "title": "Topic Modeling",
        "desc": "Discover latent topics in a corpus. Neural-LDA / BERTopic-style.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_intent",
        "icon": "target",
        "title": "Intent Detection",
        "desc": "Classify the intent of an utterance — chatbot routing, voice assistant.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "nlp",
        "key": "nlp_search",
        "icon": "search",
        "title": "Semantic Search / Retrieval",
        "desc": "Build dense retrievers — encode queries & documents into a shared embedding space.",
        "tags": "Local",
        "starter": {},
    },
    # Audio (7 total)
    {
        "cat": "audio",
        "key": "aud_classify",
        "icon": "music",
        "title": "Audio Classification",
        "desc": "Classify audio clips — environmental sounds, music genres, alarms.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "audio",
        "key": "aud_kws",
        "icon": "waves",
        "title": "Keyword Spotting",
        "desc": "On-device wake-word / command detection. Tiny CNN starter.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "audio",
        "key": "aud_asr",
        "icon": "chat",
        "title": "Speech Recognition (ASR)",
        "desc": "Transcribe spoken audio to text. CTC / encoder-decoder starter.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "audio",
        "key": "aud_tts",
        "icon": "music",
        "title": "Text-to-Speech",
        "desc": "Synthesize natural speech from text. Tacotron-style starter.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "audio",
        "key": "aud_speaker",
        "icon": "user",
        "title": "Speaker Identification",
        "desc": "Identify or verify a speaker from a voice sample.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "audio",
        "key": "aud_separate",
        "icon": "fork",
        "title": "Source Separation",
        "desc": "Separate vocals, drums, instruments from a mixed track.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "audio",
        "key": "aud_event",
        "icon": "activity",
        "title": "Sound Event Detection",
        "desc": "Detect & timestamp events in long audio — gunshots, glass breaking, machinery faults.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # Time Series (5 total)
    {
        "cat": "timeseries",
        "key": "ts_forecast",
        "icon": "activity",
        "title": "Time-Series Forecasting",
        "desc": "Predict future values — sales, demand, prices, sensor readings.",
        "tags": "Local",
        "starter": {"arch": "rnn"},
    },
    {
        "cat": "timeseries",
        "key": "ts_anomaly",
        "icon": "target",
        "title": "Time-Series Anomaly Detection",
        "desc": "Spot abnormal patterns in streaming data — fraud, equipment, infra.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "timeseries",
        "key": "ts_classify",
        "icon": "table",
        "title": "Time-Series Classification",
        "desc": "Classify whole sequences — ECG arrhythmia, gesture, activity recognition.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "timeseries",
        "key": "ts_change",
        "icon": "fork",
        "title": "Change-Point Detection",
        "desc": "Find when a process shifts regime — A/B test detection, structural breaks.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "timeseries",
        "key": "ts_imputation",
        "icon": "eraser",
        "title": "Sequence Imputation",
        "desc": "Fill missing values in a multivariate time series.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # Generative (6 total)
    {
        "cat": "generative",
        "key": "gen_vae",
        "icon": "cube",
        "title": "Variational Autoencoder",
        "desc": "Learn a smooth latent space — generate new samples, interpolate, compress.",
        "tags": "Local",
        "starter": {"arch": "vae"},
    },
    {
        "cat": "generative",
        "key": "gen_gan",
        "icon": "spark",
        "title": "GAN Image Generation",
        "desc": "Generator + discriminator pair to synthesize realistic images.",
        "tags": "Local",
        "starter": {"arch": "gan"},
    },
    {
        "cat": "generative",
        "key": "gen_diff",
        "icon": "spark",
        "title": "Diffusion Model",
        "desc": "Iteratively denoise random noise into samples — DDPM starter.",
        "tags": "Local,Preview",
        "starter": {"arch": "diffusion"},
    },
    {
        "cat": "generative",
        "key": "gen_text",
        "icon": "chat",
        "title": "Text Generation",
        "desc": "Train a small autoregressive LM that writes in your style.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "generative",
        "key": "gen_music",
        "icon": "music",
        "title": "Music Generation",
        "desc": "Generate symbolic music (MIDI) or short audio loops.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "generative",
        "key": "gen_inpaint",
        "icon": "eraser",
        "title": "Image Inpainting",
        "desc": "Fill in masked regions of an image plausibly.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # RL (5 total)
    {
        "cat": "rl",
        "key": "rl_dqn",
        "icon": "target",
        "title": "DQN — Discrete Control",
        "desc": "Q-learning agent for Atari-like or grid-world tasks.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "rl",
        "key": "rl_pg",
        "icon": "rocket",
        "title": "Policy Gradient (REINFORCE)",
        "desc": "On-policy agent that directly optimizes a stochastic policy.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "rl",
        "key": "rl_ppo",
        "icon": "rocket",
        "title": "PPO — Continuous Control",
        "desc": "Proximal Policy Optimization for robotics, locomotion, navigation.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "rl",
        "key": "rl_bandit",
        "icon": "target",
        "title": "Contextual Bandit",
        "desc": "Explore-exploit decisions with side info — recommendations, ad ranking.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "rl",
        "key": "rl_imitate",
        "icon": "user",
        "title": "Imitation / Behavior Cloning",
        "desc": "Learn a policy from expert demonstrations.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # Graph (4 total)
    {
        "cat": "graph",
        "key": "g_node",
        "icon": "network",
        "title": "Node Classification (GNN)",
        "desc": "Classify nodes in a graph — citation networks, fraud rings, social roles.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "graph",
        "key": "g_link",
        "icon": "fork",
        "title": "Link Prediction",
        "desc": "Predict missing or future edges — friend suggestions, drug-target interactions.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "graph",
        "key": "g_classify",
        "icon": "cube",
        "title": "Graph Classification",
        "desc": "Classify whole graphs — molecules, code property graphs.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "graph",
        "key": "g_kg",
        "icon": "tree",
        "title": "Knowledge-Graph Embedding",
        "desc": "Learn embeddings for entities & relations — TransE / RotatE starters.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # Multimodal (5 total)
    {
        "cat": "multimodal",
        "key": "mm_caption",
        "icon": "image",
        "title": "Image Captioning",
        "desc": "Generate a natural-language caption for an image. CNN + transformer decoder.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "multimodal",
        "key": "mm_vqa",
        "icon": "chat",
        "title": "Visual Question Answering",
        "desc": "Answer free-form questions about an image.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "multimodal",
        "key": "mm_clip",
        "icon": "fork",
        "title": "Image–Text Contrastive (CLIP-style)",
        "desc": "Train aligned image & text encoders for zero-shot classification & retrieval.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "multimodal",
        "key": "mm_avs",
        "icon": "music",
        "title": "Audio–Visual Sync",
        "desc": "Detect / align audio with video — lip sync, source localization.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "multimodal",
        "key": "mm_sensor",
        "icon": "activity",
        "title": "Sensor Fusion",
        "desc": "Combine IMU, camera, GPS, lidar for robotics & wearables.",
        "tags": "Local,Preview",
        "starter": {},
    },
    # Tools (10 total)
    {
        "cat": "tools",
        "key": "fnd_xor",
        "icon": "binary",
        "title": "XOR & Logic Gates",
        "desc": "Classic non-linearly-separable problem. Build intuition for hidden layers.",
        "tags": "Local",
        "starter": {"arch": "mlp", "task": "xor"},
    },
    {
        "cat": "tools",
        "key": "fnd_seg7",
        "icon": "grid",
        "title": "7-Segment Decoder",
        "desc": "Map 4-bit numbers to 7-segment display patterns. Multi-output classification.",
        "tags": "Local",
        "starter": {"arch": "mlp", "task": "seg7"},
    },
    {
        "cat": "tools",
        "key": "fnd_sine",
        "icon": "activity",
        "title": "Sine Approximation",
        "desc": "Fit a smooth function — pure regression intuition.",
        "tags": "Local",
        "starter": {"arch": "mlp", "task": "sine"},
    },
    {
        "cat": "tools",
        "key": "fnd_spiral",
        "icon": "spark",
        "title": "Two-Spiral Classification",
        "desc": "Hard non-linear decision boundary — tests depth, activation, and lr.",
        "tags": "Local",
        "starter": {"arch": "mlp", "task": "spiral"},
    },
    {
        "cat": "tools",
        "key": "fnd_autoenc",
        "icon": "cube",
        "title": "Toy Autoencoder",
        "desc": "8→3→8 identity compression — inspect the bottleneck.",
        "tags": "Local",
        "starter": {"arch": "mlp", "task": "autoenc"},
    },
    {
        "cat": "tools",
        "key": "fnd_blank",
        "icon": "plus",
        "title": "Blank Project (Playground)",
        "desc": "Empty canvas. Drag layers, wire them up, load any data — no scaffolding.",
        "tags": "Local",
        "starter": {"blank": True},
    },
    {
        "cat": "tools",
        "key": "fnd_distill",
        "icon": "package",
        "title": "Knowledge Distillation",
        "desc": "Teach a small student model to mimic a big teacher.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "tools",
        "key": "fnd_finetune",
        "icon": "spark",
        "title": "Fine-Tune a Pretrained Model",
        "desc": "Load weights from disk and adapt to your data with a small head.",
        "tags": "Local,Preview",
        "starter": {},
    },
    {
        "cat": "tools",
        "key": "fnd_calib",
        "icon": "target",
        "title": "Probability Calibration",
        "desc": "Improve predicted-probability quality with temperature scaling / isotonic.",
        "tags": "Local",
        "starter": {},
    },
    {
        "cat": "tools",
        "key": "fnd_explain",
        "icon": "eye",
        "title": "Model Explainability Lab",
        "desc": "SHAP, integrated gradients, attention rollout — see why the model decided.",
        "tags": "Local,Preview",
        "starter": {},
    },
]


def seed_usecases():
    """
    Populate the database with initial usecase catalog.
    Safe to run multiple times — checks for duplicates before inserting.
    """
    # Create or verify categories exist
    for cat_data in CATEGORIES_DATA:
        existing = UsecaseCategory.query.filter_by(key=cat_data["key"]).first()
        if not existing:
            cat = UsecaseCategory(
                key=cat_data["key"],
                label=cat_data["label"],
                blurb=cat_data["blurb"],
                icon=cat_data["icon"],
                color=cat_data["color"],
                display_order=cat_data["order"],
            )
            db.session.add(cat)
    db.session.commit()

    # Create or update usecases
    for uc_data in USECASES_DATA:
        # Find or create
        existing = Usecase.query.filter_by(key=uc_data["key"]).first()
        if existing:
            # Update if needed (optional)
            existing.title = uc_data["title"]
            existing.description = uc_data["desc"]
            existing.icon = uc_data["icon"]
            existing.tags = uc_data["tags"]
            existing.starter_config = uc_data["starter"]
        else:
            # Create new
            category = UsecaseCategory.query.filter_by(key=uc_data["cat"]).first()
            if not category:
                print(f"ERROR: Category '{uc_data['cat']}' not found for usecase '{uc_data['key']}'")
                continue

            uc = Usecase(
                key=uc_data["key"],
                category_id=category.id,
                title=uc_data["title"],
                description=uc_data["desc"],
                icon=uc_data["icon"],
                tags=uc_data["tags"],
                starter_config=uc_data["starter"],
                is_active=True,
            )
            db.session.add(uc)

    db.session.commit()
    print(f"✓ Seeded {len(CATEGORIES_DATA)} categories and {len(USECASES_DATA)} usecases")


if __name__ == "__main__":
    from app import create_app

    app = create_app()
    with app.app_context():
        seed_usecases()
